### ISSUE TITLE
Failed to enable plugin

### ISSUE THREAD

**Issue by HiroC222** [rabbitmq/rabbitmq-delayed-message-exchange#155]
rabbitmq version： 3.7.17
rabbitmq-delayed-message-exchange：3.8.0

rabbitmq-plugins enable rabbitmq_delayed_message_exchange

```
Enabling plugins on node rabbit@10_26_20_187:
rabbitmq_delayed_message_exchange
The following plugins have been configured:
  rabbitmq_delayed_message_exchange
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_stomp
  rabbitmq_web_dispatch
  rabbitmq_web_stomp
Applying plugin configuration to rabbit@10_26_20_187...
    (rabbitmqctl) lib/rabbitmqctl.ex:45: RabbitMQCtl.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by Yanghf123** [comment]
@HiroC222 问题有解决吗

**Comment by HiroC222** [comment]
> @HiroC222 问题有解决吗

集群不能有ram节点，保证全disk就可以用了
