### ISSUE TITLE
Can't enable rabbitmq_delayed_message_exchange With RabbitMQ 3.13.0

### ISSUE THREAD

**Issue by pnchen** [rabbitmq/rabbitmq-delayed-message-exchange#270]
### Describe the bug

Error Info:
```
# rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Enabling plugins on node rabbit@debian:
rabbitmq_delayed_message_exchange
The following plugins have been configured:
  rabbitmq_delayed_message_exchange
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_mqtt
  rabbitmq_web_dispatch
  rabbitmq_web_mqtt
Applying plugin configuration to rabbit@debian...
Stack trace:

** (CaseClauseError) no case clause matching: {:badrpc, {:EXIT, {:aborted, {:node_not_running, :rabbit@debian}}}}
    (rabbitmqctl 3.13.0-dev) lib/rabbitmq/cli/plugins/plugins_helpers.ex:215: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/2
    (rabbitmqctl 3.13.0-dev) lib/rabbitmq/cli/plugins/plugins_helpers.ex:112: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/4
    (rabbitmqctl 3.13.0-dev) lib/rabbitmq/cli/plugins/commands/enable_command.ex:127: anonymous fn/6 in RabbitMQ.CLI.Plugins.Commands.EnableCommand.do_run/2
    (elixir 1.15.4) lib/stream.ex:1530: anonymous fn/2 in Stream.iterate/2
    (elixir 1.15.4) lib/stream.ex:1757: Stream.do_unfold/4
    (elixir 1.15.4) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.15.4) lib/stream.ex:1052: Stream.do_transform_inner_enum/7
    (elixir 1.15.4) lib/stream.ex:1828: Enumerable.Stream.do_each/4

{:case_clause, {:badrpc, {:EXIT, {:aborted, {:node_not_running, :rabbit@debian}}}}}
```

the node `rabbit@debian` is running, and plugins such as `rabbitmq_mqtt`  has been enabled succesfully
![image](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/assets/2562679/9c817738-c3be-4148-a991-ac45e1912361)

### Reproduction steps

- install the latest version of rabbitmq, follow https://www.rabbitmq.com/docs/install-debian#apt-quick-start-cloudsmith
- run `rabbitmq-plugins enable rabbitmq_delayed_message_exchange`

### Expected behavior

enable the plugin without error

**Comment by mkuratczyk** [comment]
You are trying to enable a plugin while RabbitMQ is not running. Start RabbitMQ first.

**Comment by pnchen** [comment]
> You are trying to enable a plugin while RabbitMQ is not running. Start RabbitMQ first.

Thanks! In my Environment, The RabbitMQ is already started And `rabbitmq_mqtt` can be enabled successfully.

if I stop RabbitMQ by running `systemctl stop rabbitmq-server`, then run `rabbitmq-plugins enable rabbitmq_delayed_message_exchange` it will show
```
Enabling plugins on node rabbit@debian:
rabbitmq_delayed_message_exchange
The following plugins have been configured:
  rabbitmq_delayed_message_exchange
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_mqtt
  rabbitmq_web_dispatch
  rabbitmq_web_mqtt
Applying plugin configuration to rabbit@debian...
The following plugins have been enabled:
  rabbitmq_delayed_message_exchange

set 6 plugins.
Offline change; changes will take effect at broker restart.
```

But I can't start the RabbitMQ again , because rabbitmq_delayed_message_exchange will error at starting

**Comment by lukebakken** [comment]
Something similar was reported here - https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/discussions/269

@pnchen you _MUST_ provide the _EXACT_ steps you used to download and install this plugin. Please also provide the output of `ls -la` on the plugins directory in your environment.

**Comment by pnchen** [comment]
I found it because I enable the Feathure flag `khepri_db`.  When I keep this disable every thing will OK. 
<img width="887" alt="截屏2024-03-13 22 03 28" src="https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/assets/2562679/a97291e6-e532-4916-a8bc-ff1a2496c6ad">

Thanks to All

**Comment by joesdu** [comment]
> I found it because I enable the Feathure flag `khepri_db`. When I keep this disable every thing will OK. <img alt="截屏2024-03-13 22 03 28" width="887" src="https://private-user-images.githubusercontent.com/2562679/312488285-a97291e6-e532-4916-a8bc-ff1a2496c6ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk3NTEsIm5iZiI6MTcxMDMzOTQ1MSwicGF0aCI6Ii8yNTYyNjc5LzMxMjQ4ODI4NS1hOTcyOTFlNi1lNTMyLTQ5MTYtYThiYy1mZjFhMjQ5NmM2YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMTQxNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQzYjc5MDEyOTIwZThkNGM5NDVlOWIxY2I1YzgyYWI5ODVlMzI1NWFmZDY1YWI5ZTFmOTM3MDZkNDViMTNmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BB2a4XVmsnoLUCSt0xRxFXtHbvuQ1BvzSgfd6Qo_u5c">
> 
> Thanks to All

THX.
